name: Deploy to ECS

on:
  push:
    tags:
      - 'stg-be-*'
      - 'stg-fe-*'

env:
  AWS_REGION: ${{ vars.AWS_REGION }}        

jobs:
  deploy_fe_stg:
    environment: staging
    if: startsWith(github.ref, 'refs/tags/stg-fe-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract version from tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build the Frontend Docker image
        run: echo "${{ env.VERSION }}, ${{ github.sha }},  ${{ steps.login-ecr.outputs.registry }}"

      # - name: Build the Frontend Docker image
      #   run: |
      #     docker build -t ${{ secrets.AWS_ECR_REGISTRY }}/frontend:${{ env.VERSION }} ./frontend

      # - name: Push the Frontend Docker image
      #   run: |
      #     docker push ${{ secrets.AWS_ECR_REGISTRY }}/frontend:${{ env.VERSION }}

  deploy_be_stg:
    if: startsWith(github.ref, 'refs/tags/stg-be-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=$(echo ${GITHUB_REF} | sed 's/refs\/tags\/stg-be-//')" >> $GITHUB_ENV

      - name: Build the Backend Docker image
        run: |
          docker build -t ${{ secrets.AWS_ECR_REGISTRY }}/backend:${{ env.VERSION }} ./backend

      - name: Push the Backend Docker image
        run: |
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/backend:${{ env.VERSION }}